class UserNotFoundException(Exception):
    pass


class OperationalErrorException(Exception):
    pass